version: '3.7'

services:

  app:
    container_name: cushon_app
    build: .
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./
        target: /var/www/html

  mysql:
    container_name: cushon_db
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cushon
      MYSQL_ROOT_USER: root

volumes:
  app:
  db:

